### ISSUE TITLE
Colour the status bar at the bottom

### ISSUE THREAD

**Issue by buggymcbugfix** [stuartcrobinson/unique-window-colors#11]
I work full screen, with the activity bar hidden, most of the time. To make this extension useful for me I would like to change the colour of the status bar, e.g.

```json
  "workbench.colorCustomizations": {
    "statusBar.background" : "#0A2968",
    "activityBar.background": "#0A2968",
    "titleBar.activeBackground": "#0E3992",
    "titleBar.activeForeground": "#F8FAFE"
  }
```

Would you accept a PR to add this option and if yes, will you be able to point me to how to do it if I get stuck?

**Comment by buggymcbugfix** [comment]
(Sorry, I accidentally clicked "open issue" too soon)

**Comment by stuartcrobinson** [comment]
great idea!  yes would gladly accept pr.  and yes would give pointers.

**Comment by buggymcbugfix** [comment]
Argh, sorry no time at the moment. :(
