### ISSUE TITLE
Option to change color of EXPLORER-sidebar elements: "Open Editors", "Workspace"...

### ISSUE THREAD

**Issue by kaanuki** [stuartcrobinson/unique-window-colors#12]
It would be great to have the option to change color (Title-bar and/or background color)  of EXPLORER-sidebar elements: "Open Editors", "Workspace"...  I often find myself scrolling through the wrong one to find a what I'm looking for.  I get confused about where one ends and the other begins.

Just a recommendation.  

Thanks.

**Comment by stuartcrobinson** [comment]
so like when you have multiple projects open in the same VSCode window?

**Comment by stuartcrobinson** [comment]
hi kaanuki -- i don't think this is possible.  i added a feature where you can set a color for any customizable theme setting.  there aren't any for "explorer", and here you can see the options for the `sidebar`:

![explorerColorsNotPossible](https://user-images.githubusercontent.com/12928716/57196186-5b246e80-6f28-11e9-9526-65ebf3681c52.gif)
