### ISSUE TITLE
Gradient colors

### ISSUE THREAD

**Issue by LeninZapata** [stuartcrobinson/unique-window-colors#13]
Could you add gradient colors? This would make the internface cooler.
![screenshot_14](https://user-images.githubusercontent.com/42600954/53580826-6f27aa80-3b4a-11e9-9fb0-b3c402a33b8c.jpg)

**Comment by stuartcrobinson** [comment]
whoa.  that would be awesome.  how?

**Comment by LeninZapata** [comment]
![11](https://user-images.githubusercontent.com/42600954/53600164-d8bdae00-3b76-11e9-9aca-b8706065b5c5.jpg)

You could add a second color parameter: 
`example:`
```
"activityBar.background": "#B34EE9",
"titleBar.activeBackground": "#E94EBA",
"activityBar.background2": "#00FFA9",
"titleBar.activeBackground2": "#FF0000",
```
And get the gradient background
![screenshot_14](https://user-images.githubusercontent.com/42600954/53600326-4e297e80-3b77-11e9-99bc-7b75472a206f.jpg)

Can you make these changes?

**Comment by stuartcrobinson** [comment]
i still don't quite understand.  your screenshot doesn't appear to contain any gradient colors to me.  it looks like you've just changed the colors of the activity bar and title bar?

also, these parameters don't have any effect for me when i try them in my vscode settings file:

    "activityBar.background2": "#00FFA9",
    "titleBar.activeBackground2": "#FF0000",

**Comment by LeninZapata** [comment]
I have not created anything, I just ask you to add that functionality in your extension, that's all.

**Comment by stuartcrobinson** [comment]
i'm closing because i don't think this is possible.  you might be interested in the new "Animate" feature of the latest version that causes the background colors to slowly change between selected "gradient colors".
