### ISSUE TITLE
Does not seem to work with vs code 1.33

### ISSUE THREAD

**Issue by azynheira** [stuartcrobinson/unique-window-colors#16]

**Comment by azynheira** [comment]
Hi,
It does not seem to work at all with vscode 1.33. No settings file is written, so colours dont change.

Already tried with only this extension installed and the behaviour is the same.

Kind regards,
Pedro

**Comment by jasonswearingen** [comment]
I am having the same issue.  I thought I somehow messed up my settings, but I cleaned everything out, short of reinstalling VSCode entirely, and it's still broken.

**Comment by jasonswearingen** [comment]
my workaround for now is to just paste the following block into ```settings.json``` and then using a color picker extension, change the primary color on a color wheel for each setting:

```json
{
	"workbench.colorCustomizations": {
		"activityBar.background": "#33131b",
		"titleBar.activeBackground": "#421925",
		"titleBar.activeForeground": "#fbf6f7",
		"editor.background": "#50242f04"
	}
}
```

**Comment by azynheira** [comment]
Hi,
I understand, but then is fails the purpose of being random and automatic.

Kind regards,
Pedro

**Comment by stuartcrobinson** [comment]
@azynheira thanks for letting me know.  what OS are you using?  and I assume it was working fine for you previously?

**Comment by azynheira** [comment]
Hi,
I have currently at home MacOS and at work Ubuntu Linux. None of them are
currently working with version 1.33. I can also try the latest 1.32
version, but my impression is that it did not work with that one as well.
Maybe there was a vscode API change?

Kind regards,
Pedro

**Comment by jasonswearingen** [comment]
my vscode details, incuding os

```
Version: 1.33.0 (system setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

**Comment by stuartcrobinson** [comment]
ok thanks for this.  should have this resolved this week

**Comment by stuartcrobinson** [comment]
just published a revision.  let me know if it's still not working for the latest vscode version for you?

**Comment by azynheira** [comment]
Hello,
I just tested it now in MacOS and [March 2019 (version 1.33)} of VSCode and
it seems to work fine.

Thanks,
Kind regards,
Pedro

**Comment by stuartcrobinson** [comment]
awesome thanks for your help!

**Comment by azynheira** [comment]
Hi,
One thing I noticed just now is that it's adding a whole node of "
windowColors.globalData" to the global settings.json, not the workspace one.

If this is intentional, disregard my email.

Pedro

**Comment by stuartcrobinson** [comment]
Yes, that's to store different portfolios of colorations and to save
workspace colors without cluttering the filesystem with extra settings.json
files, now that colors are no longer generated by root dir hash.

**Comment by azynheira** [comment]
Hi,
I just noticed the " "BaseColor": "hsl(240,0%, 1%)"

The formatting is not ideal, but I am just being a pest now :-)

Congrats for such a nice and useful extension,

Kind regards,
Pedro

**Comment by stuartcrobinson** [comment]
yeah i threw in some random spacing to make it easier to edit colors (using the "Color Highlight" extension) in the javascript files like so:

<img width="321" alt="image" src="https://user-images.githubusercontent.com/12928716/57197592-4ef3dd80-6f37-11e9-96a9-844f9ff817ff.png">

(assuming you're seeing that in user or workspace `settings`)

and thanks! :)
