### ISSUE TITLE
Cannot Uninstall [!!!]

### ISSUE THREAD

**Issue by jrodl3r** [stuartcrobinson/unique-window-colors#17]
I have tried everything to get rid of this config for all my projects, and it seems to be stuck loading up the green titleBar + activityBar for one project.

Been tinkering with this for over an hour trying to remove/override whatever setting is being controlled for those elements background colors.

I've done the following already:

- disable the package
- remove the package from VSCode
- remove the folder in `/.vscode/extensions/`
- reset ALL VSCode Settings....

Please advise.

**Comment by jrodl3r** [comment]
Yea, I would update your README to let people know they need to remove the `.vscode` folder that gets added to their projects if they want to undo the settings (maybe I missed it?) 👍

**Comment by stuartcrobinson** [comment]
hey thank you for letting me now.  good idea for the README.  working on a next version for the extension now.  working on improving the uninstall process & docs

have you tried deleting the colors from .vscode/settings.json?

**Comment by jrodl3r** [comment]
yea, that was the most frustrating part - I couldn't undo or override the settings on a global level (in settings.json). All good 👍

**Comment by stuartcrobinson** [comment]
gotcha, cool.  makes sense.  thanks again for the feedback!

**Comment by Mark-L6n** [comment]
FYI, It appears that `.vscode/settings.json` can be used for other projects as well, so you shouldn't just automatically delete the `.vscode` folder (as suggested above).
This project appears to add the lines:

``` json
  "workbench.colorCustomizations": {
    ...
    "activityBar.background": "#312B3D",
    "titleBar.activeBackground": "#443C55",
    "titleBar.activeForeground": "#FAFAFB"
  }
```
So only those 3 lines should be deleted, if there are also other items in `workbench.colorCustomizations`.
Of course, if there is nothing else in `.vscode/settings.json`, you can go ahead and delete it ;-)

**Comment by HaveSpacesuit** [comment]
It would be kind of the extension to automatically remove those settings on uninstall.
