### ISSUE TITLE
Set color for inactive titlebar

### ISSUE THREAD

**Issue by rootix** [stuartcrobinson/unique-window-colors#18]
When i Alt+Tab trough open VSCode instances, it would be useful if they would maintain different colors in this state as well to find the correct window easier. Something like a lighter or darker variant of the active color would be nice.

Keep up the good work!

**Comment by stuart-ai** [comment]
great idea, working on this now

**Comment by stuartcrobinson** [comment]
great idea, working on this now

**Comment by stuartcrobinson** [comment]
done! feel free to let me know what you think of the inactive title bars in the latest version.  thanks for the suggestion.
