### ISSUE TITLE
Do not create project folder by default

### ISSUE THREAD

**Issue by kAlvaro** [stuartcrobinson/unique-window-colors#2]
Currently, the extension forces the creation of a `.vscode` directory on every folder you open. If you tend to use Visual Studio Code to inspect random folders you end up with your hard disc full of projects. It'd be cool if there was a way to avoid this.

Possibilities:
- Do not store colours permanently unless there're already project settings.
- Make it configurable.

If colours are based on the root dir name you should get the same colour every time anyway.

**Comment by stuart-ai** [comment]
Hi kAlvaro, thanks for the feedback!

I updated the extension to delete the `.vscode/settings.json` file as each window is closed.  As far as I know, it's not possible to change a specific window color without writing it to that file, but this should help keep the filesystem clean as you are opening and closing folders in VS Code.

**Comment by stuartcrobinson** [comment]
Hi kAlvaro, thanks for the feedback!

I updated the extension to delete the .vscode/settings.json file as each window is closed. As far as I know, it's not possible to change a specific window color without writing it to that file, but this should help keep the filesystem clean as you are opening and closing folders in VS Code.

**Comment by kAlvaro** [comment]
Has the change been published in Marketplace? In 1.0.5 it still keeps both file and directory.

It's a pity that you need permanent settings to change window colours. Considering that, it'd be nice to be able to restrict colour generation to projects that already have custom settings. But I guess that'd need to be a new ticket. Whatever, thanks for the addon!

**Comment by kAlvaro** [comment]
I don't have a `.vscode` directory in the first place (that's what the ticket was about). No idea of what's happening then :-?

**Comment by stuartcrobinson** [comment]
Is the extension modifying your colors without creating a `.vscode` folder?

I thought initially you said the problem was that it was making a `.vscode` folder in every window you opened which was cluttering your filesystem?

I have only tested it on a mac -- I'll try to test in on a PC soon.

**Comment by kAlvaro** [comment]
Colour generation works as advertised. The problem is that it isn't **removing** neither the file nor the directory afterwards.
I may test in another PC later this week if I have the chance, just to discard stuff.

**Comment by stuartcrobinson** [comment]
did you try manually deleting `.vscode/settings.json`?

**Comment by kAlvaro** [comment]
I've just tried in my other computer (Windows 10 as well) and it happens too. I start Visual Studio Code in a folder that doesn't have a previous project and it creates the `.vscode` folder the `settings.json` file. The file only contains the settings added by the extension. I close the program and both the file and the directory remain intact. I can remove them manually but when I start VSCode again the cycle repeats.

Perhaps the issue is exclusive to Windows :-?

**Comment by stuartcrobinson** [comment]
okay, i tried it on a Windows 10 EC2 instance.

one weird thing is that the first window i had open with the extension created a `.vscode/extension` directory.  but then i never saw it in vscode windows i opened later.  i never saw this folder on my mac, but it doesn't necessarily seem relevant here.

but i wasn't able to reproduce your issue.  `.vscode/settings.json` was deleted each time i closed a vscode window.

**with vscode open:**

    PS C:\Users\Public\Documents> ls .vscode
    
    
        Directory: C:\Users\Public\Documents\.vscode
    
    
    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    -a----        12/6/2018   3:31 PM            194 settings.json

**after closing vscode:**

    PS C:\Users\Public\Documents> ls .vscode
    ls : Cannot find path 'C:\Users\Public\Documents\.vscode' because it does not exist.`

what are the contents of your `.vscode` folder while your window is open?

**Comment by kAlvaro** [comment]
I think I finally found a hint of what's going on. If I run a clean set up:

     code --user-data-dir . .

... the `settings.json` file has something like this:

```
{
    "workbench.colorCustomizations": {
        "activityBar.background": "#05360E",
        "titleBar.activeBackground": "#064B13",
        "titleBar.activeForeground": "#F2FEF4"
    }
}
```
... and gets removed when I close the file. However, if I launch the program normally:

    code .

... I see:
```

{
    "workbench.colorCustomizations": {
        "tab.activeBorder": "#26A6F2",
        "tab.unfocusedActiveBorder": "#26A6F230",
        "activityBar.background": "#05360E",
        "titleBar.activeBackground": "#064B13",
        "titleBar.activeForeground": "#F2FEF4"
    }
}
```

That's because I've customised `tab.activeBorder` and `tab.unfocusedActiveBorder` in my global settings and when the extension creates project settings those two other directives get included too. Since the file has extra settings, it remains.

**Comment by stuartcrobinson** [comment]
ah, great work!  i'll work on addressing this next week.  maybe i can check to see if any `colorCustomizations` are the same as global settings.  or maybe the extension is doing something weird to cause those `tab` colors to get written to the `settings.json` file.  either way thanks for rooting this out.

**Comment by stuartcrobinson** [comment]
hey @kAlvaro - check it out!

<img width="600" alt="image" src="https://user-images.githubusercontent.com/12928716/50432722-604a2080-0899-11e9-87d9-884569e2cf76.png">

setting `Window Colors: 🌈 Delete Settings File Upon Exit` to `true` will indiscriminately delete `.vscode/settings.json` when you close the window, regardless of file contents or modifications.

(needs to be selected in `User Settings` (vs `Workspace Settings` or else it will just delete itself 💥)

let me know how this latest version works for you

**Comment by kAlvaro** [comment]
I've been playing with some local and network folders and it's been working as advertised—including the *remove workspace customizations* part ;-)

It's kind of scary and far from ideal but I guess there aren't many options left if Visual Studio Code doesn't provide an API to change colours programmatically. I have no idea if further refinements are possible or worth the time. Feel free to reopen the ticket.
