### ISSUE TITLE
Disable 

### ISSUE THREAD

**Issue by ElMakoCHEOficial** [stuartcrobinson/unique-window-colors#59]
I installed it, I tried but I didn't like it, I uninstalled it but it keeps the same color in te window and side bar 
![image_2024-06-23_201754716](https://github.com/stuartcrobinson/unique-window-colors/assets/84734574/d218b682-5ef8-4487-9caa-4df14f42e0c0)

I tried to mod in settings 
![image_2024-06-23_201937551](https://github.com/stuartcrobinson/unique-window-colors/assets/84734574/301f4c23-8684-4c50-befb-590fe3bf30c4)

still nothing
How can I change this? (PD: I'm noob😥)

**Comment by stuartcrobinson** [comment]
i haven't touched this in years but i think ...AppData.../settings.json is
the wrong file

there should be a .vscode/settings.json in your current workspace filesystem

[image: image.png]

hopefully you'll see it clicking on the Explorer icon at the top of the
left hand nav bar

**Comment by ElMakoCHEOficial** [comment]
You were right, it was in the .vscode directory in my workspace, thank you very much
