### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Josh-Cruz** [stuartcrobinson/unique-window-colors#6]
- Issue Type: `Performance`
- Extension Name: `unique-window-colors`
- Extension Version: `1.0.5`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/joshcruz/stuart.unique-window-colors-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by stuartcrobinson** [comment]
thank you for this josh!  looking into it

**Comment by stuartcrobinson** [comment]
@Josh-Cruz could you re-send that cpuprofile.txt file?

**Comment by stuartcrobinson** [comment]
@Josh-Cruz nm okay i think this is fixed.  i changed it to exit the main function if no workspace folder exists and it's no longer maxing CPU in vscode 1.20 for me (wasn't able to reproduce in 1.30).

Let me know if it's still happening for you in the latest Window Colors version.

**Comment by Josh-Cruz** [comment]
Sure Thing Bud,

Thanks for looking into it, it's a cool extension.
[stuart.unique-window-colors-unresponsive.cpuprofile.txt](https://github.com/stuartcrobinson/unique-window-colors/files/2710566/stuart.unique-window-colors-unresponsive.cpuprofile.txt)

**Comment by stuartcrobinson** [comment]
thank you for that!

i merged a change to the code that i think might have fixed your issue.  let me know if it's still causing problems for you in the latest version.
