### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tuxracer** [stuartcrobinson/unique-window-colors#8]
Awesome extension! What's the license for this repo?

**Comment by stuartcrobinson** [comment]
hey thanks and thanks for using!  haven't thought about licenses any.  there are no restrictions to usage.  is there a certain license you need it to have to use it at work or something?

**Comment by tuxracer** [comment]
just wanted to contribute but wasn't sure about the license. no big deal though not blocked on being able to use it or anything

**Comment by stuartcrobinson** [comment]
ah thanks for your interest.  contributions are very welcome!  feel free to suggest a license for instance or open a pr to add one

**Comment by stuartcrobinson** [comment]
license added -- thank you for the nudge and interest!
