### ISSUE TITLE
Option to only change the title bar

### ISSUE THREAD

**Issue by innerlee** [stuartcrobinson/unique-window-colors#9]
Option to only change the title bar only, without changing the activity bar because the activity bar is tightly coupled with color themes.

**Comment by stuartcrobinson** [comment]
thanks for using, and good idea.  i'll add this option within the next few weeks

**Comment by stuartcrobinson** [comment]
strapped for time lately.  feel free anyone to open a PR for this

**Comment by nilsborg** [comment]
Would be really cool to have this!

**Comment by nilsborg** [comment]
I have no idea how to add settings to an extension but I'll try to check it out and put in a PR if I get it working :)

**Comment by stuartcrobinson** [comment]
hey @nilsborg i'm actually working on an update for this right now that should be ready in a couple days.

**Comment by nilsborg** [comment]
Oh sweet even better!!

**Comment by stuartcrobinson** [comment]
done!  feel free to let me know what you think

<img width="422" alt="Screen Shot 2019-05-05 at 11 37 29 am" src="https://user-images.githubusercontent.com/12928716/57196360-3af5af00-6f2a-11e9-86ca-e7b1d570fc04.png">

**Comment by cdsousa** [comment]
Hi, has this been released already? I don't find the setting in 1.0.51.

**Comment by lkleuver** [comment]
ditto, is there a quick hack in the meantime?
